name: pixeltune workflow

on: 
  - push

jobs:
  unittesting:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]

    runs-on: ${{matrix.os}}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: install dependences
        run: npm install

      - name: build application
        run: npm run build

      - name: upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-build-${{matrix.node-version}}
          path: dist

      - name: test the application
        run: npm test
        continue-on-error: true


  Docker:
    runs-on: ubuntu-latest
    needs: unittesting

    steps:
      - name: docker loging
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

