name: first workflow
on: 
  - push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: list the files
        run: ls

      - name: create the files
        run: |
          touch deepu.txt
          echo "hello deepu" > deepu.txt

      - name: upload Artifacts
        uses: actions/upload-artifact@v4
        with:
           name: kanny
           path: deepu.txt


      - name: run script files
        run: |
          chmod +x .github/workflows/script.sh
          .github/workflows/script.sh


  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: kanny

  




