name: workflow 
on: 
  push:
    branches:   
    - master
    - feature
jobs:
  unittesting:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: unit testing
        run: npm install

      - name: artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: test-files
          path: node-modules/
